name: $bog_stschool_app

permissions: write-all

on:
    workflow_dispatch:
    push:
        branches: [ main ]

concurrency:
    group: deploy-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: hyoo-ru/mam_build@master2
              with:
                  package: "bog/stschool"
                  modules: 'app'
            - uses: hyoo-ru/gh-deploy@v4.4.1
              with:
                  folder: "bog/stschool/app/-"
